version: '3'
services:
  upload:
    build: .
    image: docker.quancy.com.sg/file-uploader:${VERSION-latest}
    container_name: uploader
    network_mode: bridge
    restart: always
    ports:
      - 9080:80
    volumes:
      - ./public_html/:/var/www/api.kubia.com/public_html/
    env_file:
      - .env